# Generated by Django 4.2.2 on 2023-06-22 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name or title of the skill', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief description or additional details about the skill')),
                ('years_of_experience', models.PositiveIntegerField(blank=True, help_text='Number of years of experience in the skill')),
                ('proficiency_level', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], help_text='Proficiency level in the skill (Choose from the provided options)', max_length=50)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='Name of the company or organization', max_length=100)),
                ('position', models.CharField(help_text='Job position or title', max_length=100)),
                ('responsibilities', models.TextField(blank=True, help_text='Responsibilities or tasks performed')),
                ('location', models.CharField(blank=True, help_text='Location of the company or organization', max_length=100)),
                ('start_date', models.DateField(blank=True, help_text='Start date of the experience')),
                ('end_date', models.DateField(blank=True, help_text='End date of the experience')),
                ('description', models.TextField(blank=True, help_text='Additional details or description of the experience')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(help_text='Name of the educational institution', max_length=100)),
                ('degree', models.CharField(help_text='Degree or qualification achieved', max_length=100)),
                ('field_of_study', models.CharField(help_text='Field of study or major', max_length=100)),
                ('graduation_year', models.PositiveIntegerField(blank=True, help_text='Year of graduation')),
                ('honors', models.CharField(blank=True, help_text='Honors or distinctions received', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Additional details or description of the education')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the individual', max_length=100)),
                ('contact_info', models.TextField(blank=True, help_text='Summary or description of the contact information')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254)),
                ('address', models.CharField(blank=True, help_text='Physical address', max_length=100)),
                ('website', models.URLField(blank=True, help_text='Personal website URL')),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('twitter', models.URLField(blank=True, help_text='Twitter profile URL')),
                ('github', models.URLField(blank=True, help_text='GitHub profile URL')),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
    ]
