# Generated by Django 4.2.2 on 2023-06-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_contactinformation_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year of graduation', null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, help_text='Number of years of experience in the skill', null=True),
        ),
    ]
