# Generated by Django 4.2.2 on 2023-06-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_education_graduation_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinformation',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='education',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='resume',
        ),
        migrations.AddField(
            model_name='resume',
            name='contact_information',
            field=models.ManyToManyField(blank=True, to='resume.contactinformation'),
        ),
        migrations.AddField(
            model_name='resume',
            name='educations',
            field=models.ManyToManyField(blank=True, to='resume.education'),
        ),
        migrations.AddField(
            model_name='resume',
            name='experiences',
            field=models.ManyToManyField(blank=True, to='resume.experience'),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(blank=True, to='resume.skill'),
        ),
    ]
